### ISSUE TITLE
Get Started error

### ISSUE THREAD

**Issue by TMM21042** [jaygoodswp/PHS#20]
Clicking the "Get Started" button on the Index page produces the following result/error:
![demo login error 7-28-2017](https://user-images.githubusercontent.com/26679593/28722004-32e324fc-7380-11e7-9621-68f33efc3e4d.png)

**Comment by jaygoodswp** [comment]
Yeah, I haven't hooked that button up yet. I'll have it go to the demo.

**Comment by jaygoodswp** [comment]
I've changed the link to go to the demo register page.
