### ISSUE TITLE
Demo Login Page Error

### ISSUE THREAD

**Issue by TMM21042** [jaygoodswp/PHS#21]
Attempted the demo at http://phs.goodswp.com/demo.  I used a new Username, but the same email account and same password as prior demo logins.  When submitting with the Start My Demo button, I received the following error:
![demo login error 8-2-2017](https://user-images.githubusercontent.com/26679593/28887411-1d28a362-778b-11e7-955a-e7a43dfa5548.png)

**Comment by jaygoodswp** [comment]
Okay, I'll look into it.

**Comment by jaygoodswp** [comment]
This is related to #28
