### ISSUE TITLE
Demo - Reuse of Username Stalls Verification Email

### ISSUE THREAD

**Issue by TMM21042** [jaygoodswp/PHS#34]
Test the demo page (../demo) to evaluate the email verification function.  When I use a Username that I have used before and an email address, the response from clicking on "Start My Demo) is "please wait" indefinitely.  I repeated the process using a new username and the response was the Email Popup and I received the email in my inbox.

Not sure, but I think there is something that is stalling the verification email process when a username is repeated.

**Comment by jaygoodswp** [comment]
Okay, I'll take a look.

**Comment by jaygoodswp** [comment]
This has been fixed and will be in the next release.
