### ISSUE TITLE
Demo - Use of multiple devices with email verification

### ISSUE THREAD

**Issue by TMM21042** [jaygoodswp/PHS#35]
The Email verification process seems to assume that the email is read and link clicked on the same device.  When I start the demo from a PC, but read the verification email on a mobile phone and click the link there, then the phone opens a window in its browser (to continue the demo).  I only wanted to verify the email with the phone and perform the demo on my PC (where I started it).  Can the email verification trigger a response in the PC browser session rather than open a new session on the phone?

**Comment by TMM21042** [comment]
After thinking about this specific situation a bit more, it seems to me that the link in the verification email should not open the ../demo/perform page (which happens now), but rather should be a link to continue the current session from which the visitor email was submitted.  We would need to have a unique session ID where the visitor submitted the email at the time of starting the demo.  The email link would allow that session to continue from the same browser that the visitor was using (regardless of the device that was used to open and read the email).  The session ID, and saved email address should expire after 24 hrs in case the visitor does not respond to the verification email.

**Comment by jaygoodswp** [comment]
The same session is used now; it just opens a new tab when the link is clicked.  If you inspect the link in the email, you'll notice a long sequence of characters (base64 encoded string); this is basically a session ID.  PHS will not allow access to demo/perform without it unless the user has already verified their email.  I think we can tweak it to do what you'd like.  I can add a cron job that deletes the user after 24 hours, if they have not verified their email. I can also start a timer when the Check Your Email pop-up appears and if the user verifies their address, show a button on the popup to continue the demo.

**Comment by jaygoodswp** [comment]
This has been completed and will be in the next release.  I'll also test it at that time as well.
