### ISSUE TITLE
Demo - Revise description of dragable PW parts

### ISSUE THREAD

**Issue by TMM21042** [jaygoodswp/PHS#36]
The page ../demo/perform presents the visitor with password parts and the opportunity to drag these to a preferred order.  The name used for two of the four parts in the drag and drop box is ambiguous/confusing to me.  Perhaps (for the demo) we can label the dynamic word as the "newsword" and label the other (the one from the username) as the "userword".  I think this would more clearly distinguish two of the four parts used in the drag and drop of the demo.

**Comment by jaygoodswp** [comment]
OK, I'll make it so. :)

**Comment by jaygoodswp** [comment]
This has been completed and will be in the next release.
