### ISSUE TITLE
Demo Email Verification Message - Additional Info

### ISSUE THREAD

**Issue by TMM21042** [jaygoodswp/PHS#37]
I think we should add an opening statement to the Email Verification message.  Somewhere after the "Hi username" could you add something like...
"We received a request from this email address for participation in PassHopr's Demo.
**Location:** near _City, State, Country_
**At:** _Date, Time_
**IP Address:** _ip_address_

If this wasn't you, then please accept our apologies and disregard this email."

I think this will help with erroneous use of email addresses that could create spam.

**Comment by jaygoodswp** [comment]
OK, I'll need to find an API for getting the Country and Region of the IP – City isn't usually correct.  Date, Time, IP address should be no problem.

**Comment by jaygoodswp** [comment]
This has been completed and is in the current release.
