### ISSUE TITLE
Identify IP address and browser, show to user on next login

### ISSUE THREAD

**Issue by jaygoodswp** [jaygoodswp/PHS#40]

**Comment by jaygoodswp** [comment]
@TMM21042 IP address, browser, and last login time are now tracked.  Where would you like the user to see this information?

**Comment by TMM21042** [comment]
Hi Jay;
  I don't think they need to see it for the demo.  I think we should collect it when they start a demo later compare it when they return to the demo.  If there is a match, and the email is the same, then I think we can assume it is a returning demo visitor and we do not need to send the verification email and they can proceed through the demo.  If they continue after the demo and start a free trial, or start a free trial during a separate visit, then I think we should recognize the visitor and show the visitor the IP, browser, and login time so they see we collect that and have the opportunity to recognize if it is wrong.  Does that seem reasonable?
On 9/1/2017 12:25:59 PM, jaygoodswp <notifications@github.com> wrote:
@TMM21042 [https://github.com/tmm21042] IP address, browser, and last login time are now tracked. Where would you like the user to see this information?
